export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const SET_ROOMS = 'SET_ROOMS';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const JOIN_USER = 'JOIN_USER';
export const LEAVE_USER = 'LEAVE_USER';
